# Generated by Django 5.1.1 on 2024-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/Blank profile picture.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
