# Generated by Django 5.1.1 on 2024-09-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cv_languages_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='core.cv'),
        ),
    ]
