# Generated by Django 5.1.1 on 2024-09-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contact_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experience', to='core.cv'),
        ),
    ]
