# Generated by Django 5.1.1 on 2024-09-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_cv_references_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='additional_info',
        ),
        migrations.CreateModel(
            name='AdditionaleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_info', to='core.cv')),
            ],
        ),
    ]
