# Generated by Django 5.1.1 on 2024-09-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_cv_additional_info_additionaleinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='publications',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.cv')),
            ],
        ),
    ]
