# Generated by Django 5.1.1 on 2024-09-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cv_awards_remove_cv_certifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='qualification',
        ),
    ]
